## Statistics Demonstrations


- Distributions (Binomial and Normal)
- Random Numbers
- Combinations

In [1]:
#Importing the libraries
import numpy as np
#Introducing the scipy.stats library
import scipy.stats as ss

### Distributions

##### 1. Binomial Distribution

A `binomial distribution` is utilised when the following conditions are met

- Total number of trials is fixed at **n**

- Each trial is binary, i.e., has only two possible outcomes - success or failure

- Probability of success is same in all trials, denoted by **p**

Now if you want to find the probability of **r** successes or `P(X = r)`, then you can use the following formula

![Binomial Probability Formula](images\binom.jpg)

In [2]:
#Calculating probabilites
#P (X = r)
n = 10
p = 0.4
r = 4

In [3]:
#To calculate the probability we'll use the binom.pmf
?ss.binom.pmf

In [4]:
ss.binom.pmf(r,n,p)

0.2508226560000002

In [5]:
#round the values
np.round(ss.binom.pmf(r,n,p),3)

0.251

In [6]:
#Calculating Probabilites
# P(X < = r)
#Use the binom.cdf function
?ss.binom.cdf

In [7]:
#Calculating the probabilities
np.round(ss.binom.cdf(r,n,p),3)

0.633

###### 2. Normal Distribution

![Normal Distribution](images\normd.jpg)

Let's say you're given a normal distribution with

- mean = M
- standard deviation = sd

Now you are given a value **x** and you want to compute P(X<=**x**)

In [8]:
M = 60
sd = 10
x = 40

In [9]:
#To compute P(X<=x) we use the ss.norm.cdf function
?ss.norm.cdf

In [10]:
ss.norm.cdf(x,M,sd)

0.022750131948179195

In [11]:
ss.norm(60,10).cdf(40)

0.022750131948179195

In [12]:
ss.norm.cdf(80,60,10) - ss.norm.cdf(40,60,10)

0.9544997361036416

### Random Numbers

In [13]:
#Generate random numbers belonging to a particular distribution

In [14]:
?np.random

##### 1. Binomial Distribution

For binomial distribution, given the value of **n** (the number of trials) and **p** ( the probability of success for each trial) we can generate random sequence of  possible number of successes **r** when we run this experiment multiple times.

In [27]:
?np.random.binomial

In [28]:
#Generate 10 random numbers from the binomial distribution with n = 10 and p = 0.4 
n = 1000
p = 0.4
size = 5

In [29]:
#We'll use np.random.binomial
np.random.binomial(n,p,size)

array([420, 401, 373, 388, 387])

###### 2. Normal Distribution

For normal distribution, given the value of mean (**M**) and standard deviation (**sd**) we can generate random sequence of values belonging to this distribution

In [30]:
?np.random.normal

In [31]:
#Generate 10 random numbers from the normal distribution with M = 60 and sd = 10
M = 60
sd  = 10

In [32]:
np.random.normal(M,sd,10)

array([64.65592036, 50.64319164, 62.56328553, 59.83750207, 52.70068665,
       59.56306723, 50.91009362, 73.51712969, 46.80998527, 49.56335933])

###### Seed

In order to fix the output we can set the `seed` value

In [33]:
?np.random.seed

In [39]:
seed = 100
np.random.seed(seed)

In [55]:
np.std_dev(np.random.normal(M,sd,10))

AttributeError: module 'numpy' has no attribute 'std_dev'

In [40]:
np.random.normal(M,sd,10)

array([42.50234527, 63.42680403, 71.53035803, 57.47563963, 69.81320787,
       65.14218841, 62.21179669, 49.29956669, 58.10504169, 62.55001444])

The seed has to be initialised each time you run the code to get the same output

### Combinations

Given a list containing **n** number of objects, we can find all the combinations of size **r**

In [41]:
from itertools import combinations

In [42]:
?combinations

In [43]:
alpha = 'ABCD'

In [44]:
p = combinations(alpha,2)

In [45]:
p

In [46]:
#To print the combinations
list(p)

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [60]:
alpha = ['A','B','C','D']

In [73]:
p = combinations(alpha,2)

In [74]:
list(p)

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [77]:
len(p)

TypeError: object of type 'itertools.combinations' has no len()

In [50]:
num = [1,2,3]
num

[1, 2, 3]

In [52]:
list(combinations(num,2))

[(1, 2), (1, 3), (2, 3)]

In [53]:
for c in combinations(num,2):
    if 2 in c:
        print(c)

(1, 2)
(2, 3)


In [54]:
for c in combinations(alpha,2):
    if 'A' in c:
        print(c)

('A', 'B')
('A', 'C')
('A', 'D')


In [57]:
result = tuple([1,2])
print(result)

(1, 2)


In [79]:
ss.binom.pmf(3,12,8/12)*((12/4)**9)

65.18518518518528

In [83]:
ss.binom.cdf(4,4,1/6)-ss.binom.cdf(-1,4,1/6)

1.0

In [81]:
ss.binom.pmf(2,4,1/6)

0.11574074074074078

In [84]:
nums = [1,2,3,4]

In [85]:
len(nums)

4

In [86]:
max(nums)

4