In [1]:
import numpy as np
import pandas as pd

#pokemon = np.read_csv('pokemon.csv')

In [4]:
pokemon.head

<bound method NDFrame.head of         Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]>

In [5]:
pokemons = open('pokemon.csv').readlines()

In [6]:
type(pokemons)

list

In [10]:
list_ = range(2,3)

for i in list:
    print(i)

2


In [1]:
n=int(input()) # lets give input as 2

answer=[[1]] #2
for i in range(2, n+1):   # i in range 2,3
    print('Outer for loop')
    t=[i]*((2*i)-3) # t=[2]*1
    answer.insert(0, t) # 2 before
    answer.append(t) # 2 after
    print(answer)
    for a in answer:
        print('Inner for loop')
        a.insert(0,i) # 2 before
        a.append(i) # 2 after
        print(a)

2
Outer for loop
[[2], [1], [2]]
Inner for loop
[2, 2, 2]
Inner for loop
[2, 1, 2]
Inner for loop
[2, 2, 2, 2, 2]


In [4]:
loans = pd.read_csv("Inferential Statistics - Student Loan.csv")

In [12]:
loans.head()

Customer No.  Exposure at Default (in lakh Rs.)  Recovery (%)  \
0             1                              11.50        0.2000   
1             2                               0.24        0.0510   
2             3                               0.04        0.2486   
3             4                              13.81        0.0229   
4             5                              19.84        0.0347   

   Probability of Default  Unnamed: 4  Unnamed: 5  Expected Loss  
0                  0.0070         NaN         NaN       0.064400  
1                  0.0033         NaN         NaN       0.000752  
2                  0.0022         NaN         NaN       0.000066  
3                  0.0066         NaN         NaN       0.089059  
4                  0.0020         NaN         NaN       0.038303

In [7]:
loans['Recovery (%)'] = loans['Recovery (%)'].apply(lambda x:x[:-1])
loans['Recovery (%)'] = loans['Recovery (%)'].astype('float')/100

In [13]:
loans['Expected Loss'].mean()

0.04933913144062013

In [9]:
loans['Expected Loss'] = loans['Exposure at Default (in lakh Rs.)']*loans['Probability of Default']*(1-loans['Recovery (%)'])

In [10]:
sum(loans['Expected Loss'])

493.39131440620133

In [11]:
import scipy.stats as ss

In [15]:
ss.ttest_1samp(loans['Expected Loss'],0.049)

Ttest_1sampResult(statistic=0.7569565378629165, pvalue=0.44909373694968524)

In [16]:
ss.ttest_ind(loans['Expected Loss'],loans['Exposure at Default (in lakh Rs.)'])

Ttest_indResult(statistic=-171.25889416133865, pvalue=0.0)

In [1]:
import pandas as pd 
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/8NMooe4G0ENEe8z9q5ZvaZA7/googleplaystore.csv")
#add your cleaning code here

In [33]:
df.shape

(10841, 13)

In [34]:
df = df[~(df['Installs']=='Free')]

In [35]:
df.shape

(10840, 13)

In [36]:
df[['Installs']]

Installs
0          10,000+
1         500,000+
2       5,000,000+
3      50,000,000+
4         100,000+
...            ...
10836       5,000+
10837         100+
10838       1,000+
10839       1,000+
10840  10,000,000+

[10840 rows x 1 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10840 non-null  object 
 1   Category        10840 non-null  object 
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  object 
 4   Size            10840 non-null  object 
 5   Installs        10840 non-null  object 
 6   Type            10839 non-null  object 
 7   Price           10840 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10840 non-null  object 
 10  Last Updated    10840 non-null  object 
 11  Current Ver     10832 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), object(12)
memory usage: 1.2+ MB


In [38]:
df['Installs'] = df['Installs'].apply(lambda x: x.replace('+',''))
df['Installs'] = df['Installs'].apply(lambda x: x.replace(',',''))

In [39]:
df[['Installs']]

Installs
0         10000
1        500000
2       5000000
3      50000000
4        100000
...         ...
10836      5000
10837       100
10838      1000
10839      1000
10840  10000000

[10840 rows x 1 columns]

In [40]:
df[['Installs']] = df[['Installs']].astype('int')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10840 non-null  object 
 1   Category        10840 non-null  object 
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  object 
 4   Size            10840 non-null  object 
 5   Installs        10840 non-null  int32  
 6   Type            10839 non-null  object 
 7   Price           10840 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10840 non-null  object 
 10  Last Updated    10840 non-null  object 
 11  Current Ver     10832 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), int32(1), object(11)
memory usage: 1.1+ MB


In [25]:
import pandas as pd
import ast,sys
df=pd.read_csv("https://media-doselect.s3.amazonaws.com/generic/X0kvr3wEYXRzONE5W37xWWYYA/test.csv")

In [26]:
df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [27]:
to_omit =  ['Pclass','Age']

In [28]:
all_col = set(df.columns)
set_omit = set(to_omit)

In [29]:
cols = list(all_col - set_omit)

In [30]:
type(cols)

list

In [32]:
df = df[cols].sort_index(axis=1,inplace=True)

C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [33]:
df.head()

AttributeError: 'NoneType' object has no attribute 'head'

In [20]:
to_omit

['Pclass', 'Age']

In [ ]:
df = df.drop(to_omit,axis=1)
df.sort_index(axis=1,inplace=True)
print(df.head())

In [7]:
'''IMPORTANT: click on "Compile & Run" to generate an output to the written code
ONLY this will generate scores for your code!
Also this will help you to check correctness of your code against test cases'''

#this is default OUTPUT. You are allowed to modify it.
result=-404.000

#INPUT [uncomment & modify if required]

#input for number of records given as input
n=int(input())

#input for the n records. Each record denotes Sex, Age, Weight, Temperature.
for i in range(n):
    print(line[0],end=" ")
    print(line[1],end=" ")
    print(weight,end=" ")
    print(temp)
	line=input().split(' ')
	temp=float(line[3])
	weight=float(line[2])
	if temp>=96 and temp<=109:
	    temp = round(5*(temp-32)/9,3)
	    weight = round(weight/2.2046,3)

	
#NOTE: The input now contains n records and each record contains Sex, Age, Weight, Temperature.

#WRITE YOUR LOGIC HERE:


#OUTPUT [uncomment & modify if required] 
print("%.3f" % result)

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-7-d920b3faf6ff>, line 19)

In [3]:
A = np.array([[2,1,1],[3,2,1],[2,1,2]])

In [4]:
B = np.linalg.inv(A)

In [5]:
B

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [6]:
C = A @ B

In [7]:
C

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 0.0000000e+00, 1.0000000e+00]])

In [2]:
A = np.array([[1,2],[1,-1]])

In [3]:
B = np.array([[1,0],[0,1]])

In [4]:
C = np.linalg.inv(B)

In [5]:
M = C @ A

In [6]:
M

array([[ 1.,  2.],
       [ 1., -1.]])

In [2]:
A = np.array([[1,2],[1,1]])

In [7]:
v2 = np.array([[1],[1]])

In [8]:
A @ v2

array([[3],
       [2]])

In [15]:
B2 = np.array([[3,-3],[4,-5]])

In [16]:
M = np.linalg.inv(B2)

In [18]:
v1 = np.array([[3],[2]])

In [20]:
M @ v1

array([[3.],
       [2.]])

In [17]:
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [19]:
v1

array([[3],
       [2]])

In [2]:
import pandas as pd

In [3]:
pca_data = pd.read_csv('Ratings.csv')

In [4]:
pca_data

B1  B2  B3  B4  B5
0   1   0   4   0   3
1   2   3   4   3   2
2   3   3   2   4   2
3   4   4   3   5   4
4   5   1   4   2   2
5   4   2   4   3   4
6   4   3   1   5   5

In [5]:
from sklearn.decomposition import PCA

In [6]:
pca = PCA(random_state=42)

In [7]:
pcas = pca.fit_transform(pca_data)

In [8]:
pca.fit(pca_data).explained_variance_ratio_

array([6.51886873e-01, 1.52836342e-01, 1.30717403e-01, 6.43810220e-02,
       1.78359842e-04])